name: manage-azure-policy-2c659cb6
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'qualys_v1/policies/IRAS_SG_Policy_PreProd_Qualys_v1_d229ba93-1707-4f34-bb29-107cafa8d3ad/**'
#      - .github/workflows/manage-azure-policy-2c659cb6.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_2c659cb6}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          qualys_v1/policies/IRAS_SG_Policy_PreProd_Qualys_v1_d229ba93-1707-4f34-bb29-107cafa8d3ad/**
